"""Add email to User model

Revision ID: 2b2ccd0d83a1
Revises: b39497af5457
Create Date: 2025-08-23 12:09:46.959985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2ccd0d83a1'
down_revision: Union[str, None] = 'b39497af5457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashedPassword', sa.String(), nullable=False))
    op.add_column('users', sa.Column('isActive', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'isActive')
    op.drop_column('users', 'hashedPassword')
    # ### end Alembic commands ###
