"""Create protocols table

Revision ID: 3f055107e978
Revises: 
Create Date: 2025-09-17 17:03:15.658002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f055107e978'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolId', sa.String(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=True),
    sa.Column('protocolClassName', sa.String(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('parentIds', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('childIds', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocolId')
    )
    with op.batch_alter_table('protocols', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protocols_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('protocols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protocols_id'))

    op.drop_table('protocols')
    # ### end Alembic commands ###
