"""Add extra fields to User

Revision ID: 73486c4016b5
Revises: edf39f62a66f
Create Date: 2025-08-30 06:49:04.977320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73486c4016b5'
down_revision: Union[str, None] = 'edf39f62a66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('postalCode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'postalCode')
    op.drop_column('users', 'city')
    op.drop_column('users', 'country')
    op.drop_column('users', 'position')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
