"""Add isVerified to users

Revision ID: edf39f62a66f
Revises: cefec59a5897
Create Date: 2025-08-29 12:52:41.996573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf39f62a66f'
down_revision: Union[str, None] = 'cefec59a5897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isVerified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verificationCode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verificationCode')
    op.drop_column('users', 'isVerified')
    # ### end Alembic commands ###
