[localhost]
PARALLEL_COMMAND = mpirun -np %_(JOB_NODES)d %_(COMMAND)s
NAME = SLURM
MANDATORY = False
SUBMIT_COMMAND = sbatch --parsable %_(JOB_SCRIPT)s
CANCEL_COMMAND = scancel %_(JOB_ID)s
CHECK_COMMAND = squeue -h -j %_(JOB_ID)s
SUBMIT_PREFIX = scipion
SUBMIT_TEMPLATE = #!/bin/bash
    ### Inherit all current environment variables
    #SBATCH --export=ALL
    ### Job name
    #SBATCH -J %_(JOB_NAME)s
    ### Outputs
    #SBATCH -o %_(JOB_SCRIPT)s.out
    #SBATCH -e %_(JOB_SCRIPT)s.err
    #SBATCH --open-mode=append
    ### Partition (queue) name
    #SBATCH -p %_(JOB_QUEUE)s
    ### Specify time, number of nodes (tasks), cores and memory(MB) for your job
    #SBATCH --time=%_(JOB_TIME)s:00:00 --ntasks=%_(JOB_NODES)d --cpus-per-task=%_(JOB_THREADS)d --mem=%_(JOB_MEMORY)s --gres=gpu:%_(GPU_COUNT)s

    %_(JOB_COMMAND)s
    
QUEUES = {    
    	"debug": [["JOB_MEMORY", "8192", "Memory (MB)", "Select amount of memory in megabytes for this job"],
        ["JOB_TIME", "2", "Time (hours)", "Select the expected time in hours for this job"],
        ["GPU_COUNT", "1", "Number of GPUs", "Select number of GPUs for this job"],
         ["QUEUE_FOR_JOBS", "N", "Use queue for jobs", "Send individual jobs to queue"]]   
    }
